### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by GrifP** [p2pu/how-to-talk-about-race#5]
- [x] About nav text isn't highlighted when it's selected
- [x] From 767p to 935p the hamburger disappears and text bleeds beyond the right side of the screen
- [ ] From 936 to 1235px to spacing between items is off

**Comment by dirkcuys** [comment]
> From 936 to 1235px to spacing between items is off

This is an problem with bootstrap navs and text that wraps:

![image](https://user-images.githubusercontent.com/121995/110602967-2f5f1900-818f-11eb-9e4e-5237e949c35c.png)

**Comment by dirkcuys** [comment]
ps. setting `flex-basis: 0;` on `.navbar-nav` using a media query when size is roughly 936 to 1235px would help a little
