### ISSUE TITLE
Merge CIAB update for title spacing

### ISSUE THREAD

**Issue by GrifP** [p2pu/how-to-talk-about-race#8]
Replace %20 with -

**Comment by dirkcuys** [comment]
@beckymargraf have a look at how I did it here: https://github.com/p2pu/how-to-talk-about-race/blob/gh-pages/_data/course.yml

Which way would you prefer, this or the way I changed it for the AI course?

**Comment by beckymargraf** [comment]
Oh, this level of control is great! I like this a lot.

**Comment by dirkcuys** [comment]
I created a issue for it on Course in a Box: https://github.com/p2pu/course-in-a-box/issues/135
